# Generated by Django 3.2 on 2021-05-02 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.time),
            preserve_default=False,
        ),
    ]
