# Generated by Django 3.2.1 on 2021-05-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0010_remove_joke_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='joke_id',
        ),
    ]
